[tools]
php = "8.2"
node = "22"

[env]
_.path = ["./node_modules/.bin", "./vendor/bin"]
wp_script_flags = "--experimental-modules --webpack-copy-php --blocks-manifest"

[tasks.install-deps]
depends = ["install-js-deps", "install-php-deps"]

[tasks.install-php-deps]
sources = ["composer.json"]
outputs = ["composer.lock"]
run = "composer install && touch composer.lock"

[tasks.install-js-deps]
sources = ["package.json"]
outputs = ["package-lock.json"]
run = "npm install && touch package-lock.json"

[tasks.dev]
depends = ["env-start", "scripts-start"]

[tasks.start]
depends = ["env-start", "scripts-build"]

[tasks.stop]
depends = ["env-stop"]

[tasks.build]
depends = ["scripts-build"]

[tasks.clean]
depends = ["clean-build", "clean-zip"]

[tasks.format]
depends = ["install-deps"]
run = "wp-scripts format"

[tasks.lint]
depends = ["lint-css", "lint-js"]

[tasks.lint-css]
depends = ["install-deps"]
run = "wp-scripts lint-style"

[tasks.lint-js]
depends = ["install-deps"]
run = "wp-scripts lint-js"

[tasks.packages-update]
depends = ["install-deps"]
run = "wp-scripts packages-update"

[tasks.build-zip]
depends = ["build", "clean-mo"]
run = "wp-scripts plugin-zip"

[tasks.create-block]
run = """
cd src/blocks
pnpx @wordpress/create-block@latest \
    --no-plugin \
    --variant dynamic \
    --namespace=nashvilleccr \
    --textdomain=nccr
"""

[tasks.scripts-build]
depends = ["install-deps", "clean-build"]
run = "wp-scripts build ${wp_script_flags}"

[tasks.scripts-start]
depends = ["install-deps", "clean-build"]
run = "wp-scripts start ${wp_script_flags}"

[tasks.env-start]
run = "if [ -z \"$(docker ps -q)\" ]; then wp-env start; fi"

[tasks.env-after-start]
run = """\
#!/bin/bash
script=$(cat <<EOF
PLUGIN_DIR="wp-content/plugins/nashvilleccr-ext"
if [ -e "\\${PLUGIN_DIR}/imports.xml" ]; then
    wp import --authors=skip "\\${PLUGIN_DIR}/imports.xml"
fi
wp theme activate kadence
wp option update blogname "Nashville CCR (Development)"
wp option update options_google_api_key "${GOOGLE_API_KEY}"
wp option update _options_google_api_key field_68c843793f52b
wp option update options_disable_emoji_support 1
wp option update _options_disable_emoji_support field_68bf2b1301f88
wp option update options_load_separate_core_block_assets 1
wp option update _options_load_separate_core_block_assets field_68bf2b3e01f89
wp option update options_remove_block_css_globals 1
wp option update _options_remove_block_css_globals field_68bf2bb601f8a
wp option update options_disable_classic_theme_css 1
wp option update _options_disable_classic_theme_css field_68bf2bd201f8b
wp option update polylang --json '{"force_lang":1,"domains":[],"hide_default":true,"rewrite":true,"redirect_lang":false,"browser":false,"media_support":false,"post_types":[],"taxonomies":[],"sync":[],"default_lang":"en","nav_menus":[],"language_taxonomies":[],"first_activation":1760302027,"previous_version":"","version":"3.7.3"}'
wp rewrite structure --hard '/%postname%/'
EOF
)
wp-env run cli bash -c "$script"
"""

[tasks.env-restart]
run = "wp-env start"

[tasks.env-update]
run = "wp-env start --update"

[tasks.env-stop]
run = "wp-env stop"

[tasks.clean-mo]
run = "rm -f languages/nccr-*_*.mo"

[tasks.clean-build]
run = "rm -rf build"

[tasks.clean-zip]
run = "rm -f nashvilleccr-ext.zip"

[tasks.deploy]
depends = ["activate-zip"]
depends_post = ["clean-zip"]

[tasks.activate-zip]
depends = ["upload-zip"]
run = """ssh -t ${SSH_USER}@${SSH_HOST} <<EOF
#!/bin/bash
cd ${REMOTE_WWW_DIR}
wp plugin install --force ${REMOTE_TMP_DIR}/nashvilleccr-ext.zip
rm ${REMOTE_TMP_DIR}/nashvilleccr-ext.zip
EOF
"""

[tasks.upload-zip]
depends = ["build-zip"]
run = "scp nashvilleccr-ext.zip ${SSH_USER}@${SSH_HOST}:${REMOTE_TMP_DIR}/"

[tasks.repl]
depends = ["env-start"]
run = "wp-env run cli bash"

[tasks.make-pot]
run = """wp i18n make-pot \
    . \
    languages/nccr.pot \
    --slug=nashvilleccr-ext \
    --domain=nccr \
    --exclude=.git,.vscode,build,node_modules,vendor
"""