<?php namespace NashvilleCCR; defined('ABSPATH') || exit;

class RegisterFields {
    static function load() {
        self::register_fields();
    }

    static function register_fields() {
        add_action('acf/include_fields', function () {
            if (! function_exists('acf_add_local_field_group')) {
                return;
            }

            acf_add_local_field_group(array(
                'key' => 'group_68a513cf030d3',
                'title' => 'Contact',
                'fields' => array(
                    array(
                        'key' => 'field_68a513d0ed2e2',
                        'label' => 'Email',
                        'name' => 'email',
                        'aria-label' => '',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68a5145fed2e3',
                        'label' => 'Phone',
                        'name' => 'phone',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'contact',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_68c84377934f6',
                'title' => 'Environment',
                'fields' => array(
                    array(
                        'key' => 'field_68c843793f52b',
                        'label' => 'Google API Key',
                        'name' => 'google_api_key',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Requires "Maps JavaScript API" permissions.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'nashville-ccr-ext',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'left',
                'instruction_placement' => 'field',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_68a4970239b87',
                'title' => 'Event',
                'fields' => array(
                    array(
                        'key' => 'field_68a497022d5eb',
                        'label' => 'Schedule',
                        'name' => 'schedule',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'pagination' => 0,
                        'min' => 1,
                        'max' => 0,
                        'collapsed' => 'field_68a497852d5ec',
                        'button_label' => 'Add Row',
                        'rows_per_page' => 20,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_68a497852d5ec',
                                'label' => '',
                                'name' => 'time',
                                'aria-label' => '',
                                'type' => 'date_time_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'display_format' => 'F j, Y g:i a',
                                'return_format' => 'Y-m-d H:i:s',
                                'first_day' => 1,
                                'allow_in_bindings' => 0,
                                'default_to_current_date' => 0,
                                'parent_repeater' => 'field_68a497022d5eb',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_68a4985d8e31a',
                        'label' => 'Location',
                        'name' => 'location',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'location',
                        ),
                        'post_status' => array(
                            0 => 'publish',
                        ),
                        'taxonomy' => '',
                        'return_format' => 'object',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 1,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => array(),
                    ),
                    array(
                        'key' => 'field_68a498798e31b',
                        'label' => 'Contacts',
                        'name' => 'contacts',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'contact',
                        ),
                        'post_status' => array(
                            0 => 'publish',
                        ),
                        'taxonomy' => '',
                        'return_format' => 'object',
                        'multiple' => 1,
                        'allow_null' => 0,
                        'allow_in_bindings' => 1,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => array(),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'event',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_68a251f5d8ab8',
                'title' => 'Group',
                'fields' => array(
                    array(
                        'key' => 'field_68a4934770018',
                        'label' => 'Schedule',
                        'name' => 'schedule',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'pagination' => 0,
                        'min' => 1,
                        'max' => 0,
                        'collapsed' => 'field_68a4941b70019',
                        'button_label' => 'Add Row',
                        'rows_per_page' => 20,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_68a4941b70019',
                                'label' => 'Day',
                                'name' => 'day',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    0 => 'Sunday',
                                    1 => 'Monday',
                                    2 => 'Tuesday',
                                    3 => 'Wednesday',
                                    4 => 'Thursday',
                                    5 => 'Friday',
                                    6 => 'Saturday',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                                'create_options' => 0,
                                'save_options' => 0,
                                'parent_repeater' => 'field_68a4934770018',
                            ),
                            array(
                                'key' => 'field_68a494707001a',
                                'label' => 'Time',
                                'name' => 'time',
                                'aria-label' => '',
                                'type' => 'time_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'display_format' => 'g:i a',
                                'return_format' => 'H:i:s',
                                'allow_in_bindings' => 0,
                                'parent_repeater' => 'field_68a4934770018',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_68a3a9073171a',
                        'label' => 'Location',
                        'name' => 'location',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'location',
                        ),
                        'post_status' => array(
                            0 => 'publish',
                        ),
                        'taxonomy' => '',
                        'return_format' => 'object',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => array(),
                    ),
                    array(
                        'key' => 'field_68a251fecc654',
                        'label' => 'Contacts',
                        'name' => 'contacts',
                        'aria-label' => '',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                            0 => 'contact',
                        ),
                        'post_status' => array(
                            0 => 'publish',
                        ),
                        'taxonomy' => '',
                        'return_format' => 'object',
                        'multiple' => 1,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'bidirectional' => 0,
                        'ui' => 1,
                        'bidirectional_target' => array(),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'group',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_68a5154c2f6e1',
                'title' => 'Location',
                'fields' => array(
                    array(
                        'key' => 'field_68a5154d3980e',
                        'label' => 'Address',
                        'name' => 'address',
                        'aria-label' => '',
                        'type' => 'google_map',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'center_lat' => '',
                        'center_lng' => '',
                        'zoom' => '',
                        'height' => '',
                        'allow_in_bindings' => 0,
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'location',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));

            acf_add_local_field_group(array(
                'key' => 'group_68bf2b1042c9f',
                'title' => 'Performance',
                'fields' => array(
                    array(
                        'key' => 'field_68bf2b1301f88',
                        'label' => 'Disable Emoji Support',
                        'name' => 'disable_emoji_support',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'allow_in_bindings' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'ui' => 1,
                    ),
                    array(
                        'key' => 'field_68bf2b3e01f89',
                        'label' => 'Load Separate Core Block Assets',
                        'name' => 'load_separate_core_block_assets',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'allow_in_bindings' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'ui' => 1,
                    ),
                    array(
                        'key' => 'field_68bf2bb601f8a',
                        'label' => 'Remove Block CSS Globals',
                        'name' => 'remove_block_css_globals',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'allow_in_bindings' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'ui' => 1,
                    ),
                    array(
                        'key' => 'field_68bf2bd201f8b',
                        'label' => 'Disable Classic Theme CSS',
                        'name' => 'disable_classic_theme_css',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'allow_in_bindings' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'ui' => 1,
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'nashville-ccr-ext',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'left',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        });

        add_action('init', function () {
            register_post_type('contact', array(
                'labels' => array(
                    'name' => 'Contacts',
                    'singular_name' => 'Contact',
                    'menu_name' => 'Contacts',
                    'all_items' => 'All Contacts',
                    'edit_item' => 'Edit Contact',
                    'view_item' => 'View Contact',
                    'view_items' => 'View Contacts',
                    'add_new_item' => 'Add Contact',
                    'add_new' => 'Add Contact',
                    'new_item' => 'New Contact',
                    'parent_item_colon' => 'Parent Contact:',
                    'search_items' => 'Search Contacts',
                    'not_found' => 'No contacts found',
                    'not_found_in_trash' => 'No contacts found in Trash',
                    'archives' => 'Contact Archives',
                    'attributes' => 'Contact Attributes',
                    'insert_into_item' => 'Insert into contact',
                    'uploaded_to_this_item' => 'Uploaded to this contact',
                    'filter_items_list' => 'Filter contacts list',
                    'filter_by_date' => 'Filter contacts by date',
                    'items_list_navigation' => 'Contacts list navigation',
                    'items_list' => 'Contacts list',
                    'item_published' => 'Contact published.',
                    'item_published_privately' => 'Contact published privately.',
                    'item_reverted_to_draft' => 'Contact reverted to draft.',
                    'item_scheduled' => 'Contact scheduled.',
                    'item_updated' => 'Contact updated.',
                    'item_link' => 'Contact Link',
                    'item_link_description' => 'A link to a contact.',
                ),
                'public' => true,
                'show_in_rest' => true,
                'menu_position' => 30,
                'menu_icon' => 'dashicons-info',
                'supports' => array(
                    0 => 'title',
                    1 => 'editor',
                    2 => 'thumbnail',
                    3 => 'custom-fields',
                ),
                'delete_with_user' => false,
            ));

            register_post_type('event', array(
                'labels' => array(
                    'name' => 'Events',
                    'singular_name' => 'Event',
                    'menu_name' => 'Events',
                    'all_items' => 'All Events',
                    'edit_item' => 'Edit Event',
                    'view_item' => 'View Event',
                    'view_items' => 'View Events',
                    'add_new_item' => 'Add Event',
                    'add_new' => 'Add Event',
                    'new_item' => 'New Event',
                    'parent_item_colon' => 'Parent Event:',
                    'search_items' => 'Search Events',
                    'not_found' => 'No events found',
                    'not_found_in_trash' => 'No events found in Trash',
                    'archives' => 'Event Archives',
                    'attributes' => 'Event Attributes',
                    'insert_into_item' => 'Insert into event',
                    'uploaded_to_this_item' => 'Uploaded to this event',
                    'filter_items_list' => 'Filter events list',
                    'filter_by_date' => 'Filter events by date',
                    'items_list_navigation' => 'Events list navigation',
                    'items_list' => 'Events list',
                    'item_published' => 'Event published.',
                    'item_published_privately' => 'Event published privately.',
                    'item_reverted_to_draft' => 'Event reverted to draft.',
                    'item_scheduled' => 'Event scheduled.',
                    'item_updated' => 'Event updated.',
                    'item_link' => 'Event Link',
                    'item_link_description' => 'A link to a event.',
                ),
                'public' => true,
                'show_in_rest' => true,
                'menu_icon' => 'dashicons-calendar-alt',
                'supports' => array(
                    0 => 'title',
                    1 => 'editor',
                    2 => 'thumbnail',
                    3 => 'custom-fields',
                ),
                'delete_with_user' => false,
            ));

            register_post_type('group', array(
                'labels' => array(
                    'name' => 'Groups',
                    'singular_name' => 'Group',
                    'menu_name' => 'Groups',
                    'all_items' => 'All Groups',
                    'edit_item' => 'Edit Group',
                    'view_item' => 'View Group',
                    'view_items' => 'View Groups',
                    'add_new_item' => 'Add Group',
                    'add_new' => 'Add Group',
                    'new_item' => 'New Group',
                    'parent_item_colon' => 'Parent Group:',
                    'search_items' => 'Search Groups',
                    'not_found' => 'No groups found',
                    'not_found_in_trash' => 'No groups found in Trash',
                    'archives' => 'Group Archives',
                    'attributes' => 'Group Attributes',
                    'insert_into_item' => 'Insert into group',
                    'uploaded_to_this_item' => 'Uploaded to this group',
                    'filter_items_list' => 'Filter groups list',
                    'filter_by_date' => 'Filter groups by date',
                    'items_list_navigation' => 'Groups list navigation',
                    'items_list' => 'Groups list',
                    'item_published' => 'Group published.',
                    'item_published_privately' => 'Group published privately.',
                    'item_reverted_to_draft' => 'Group reverted to draft.',
                    'item_scheduled' => 'Group scheduled.',
                    'item_updated' => 'Group updated.',
                    'item_link' => 'Group Link',
                    'item_link_description' => 'A link to a group.',
                ),
                'public' => true,
                'show_in_rest' => true,
                'menu_icon' => 'dashicons-groups',
                'supports' => array(
                    0 => 'title',
                    1 => 'editor',
                    2 => 'thumbnail',
                    3 => 'custom-fields',
                ),
                'delete_with_user' => false,
            ));

            register_post_type('location', array(
                'labels' => array(
                    'name' => 'Locations',
                    'singular_name' => 'Location',
                    'menu_name' => 'Locations',
                    'all_items' => 'All Locations',
                    'edit_item' => 'Edit Location',
                    'view_item' => 'View Location',
                    'view_items' => 'View Locations',
                    'add_new_item' => 'Add Location',
                    'add_new' => 'Add Location',
                    'new_item' => 'New Location',
                    'parent_item_colon' => 'Parent Location:',
                    'search_items' => 'Search Locations',
                    'not_found' => 'No locations found',
                    'not_found_in_trash' => 'No locations found in Trash',
                    'archives' => 'Location Archives',
                    'attributes' => 'Location Attributes',
                    'insert_into_item' => 'Insert into location',
                    'uploaded_to_this_item' => 'Uploaded to this location',
                    'filter_items_list' => 'Filter locations list',
                    'filter_by_date' => 'Filter locations by date',
                    'items_list_navigation' => 'Locations list navigation',
                    'items_list' => 'Locations list',
                    'item_published' => 'Location published.',
                    'item_published_privately' => 'Location published privately.',
                    'item_reverted_to_draft' => 'Location reverted to draft.',
                    'item_scheduled' => 'Location scheduled.',
                    'item_updated' => 'Location updated.',
                    'item_link' => 'Location Link',
                    'item_link_description' => 'A link to a location.',
                ),
                'public' => true,
                'show_in_rest' => true,
                'menu_icon' => 'dashicons-location',
                'supports' => array(
                    0 => 'title',
                    1 => 'editor',
                    2 => 'thumbnail',
                    3 => 'custom-fields',
                ),
                'delete_with_user' => false,
            ));
        });

        add_action('acf/init', function () {
            acf_add_options_page(array(
                'page_title' => 'Nashville CCR Ext',
                'menu_slug' => 'nashville-ccr-ext',
                'parent_slug' => 'options-general.php',
                'position' => '',
                'redirect' => false,
            ));
        });
    }
}